project_id: "879016"
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."

files:
  - source: /app/src/main/res/values/strings.xml
    ignore:
      - /app/src/main/res/values-night/**
    translation: /app/src/main/res/values-%two_letters_code%/strings.xml
    type: android
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        zh-TW: zh-rTW
  - source: /app/src/main/res/values/plurals.xml
    ignore:
      - /app/src/main/res/values-night/**
    translation: /app/src/main/res/values-%two_letters_code%/plurals.xml
    type: android
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        zh-TW: zh-rTW
